### PR TITLE
Transpiler: Refactor `RuleDefinition::find` and remove `RuleDefinition::get_node`

### LINKED ISSUE #73: Transpiler: Refactor `RuleDefinition::find` and remove `RuleDefinition::get_node`
The implementation of `RuleDefinition` does not work well with more deeper ASTs. For example, a `SYSDATE` may be present at the top of a block, but also further-down, inside a nested block. `RuleDefinition::get_node` returns only a single node (for example the procedure body), which is then passed on to `RuleDefinition::apply`. As the `replace_token` function can only work if the token is a direct child of the node, this approach becomes really cumbersome.

## Goal

Remove the `RuleDefinition::get_node` in favour of returning `Vec<(SyntaxNode, TextRange)>` for `RuleDefinition::find`.
This will enable the removal of the `get_nvl_nodes` and `get_sysdate_nodes` helper functions.

## How to demo

All tests pass using the new `RuleDefinition::find`.

### PR DESCRIPTION
**Pull request by KieranKaelin**
Closes #73.

### CODE REVIEW

File: src/rules/builtins.rs [hunk 1]
```diff
@@ -22,17 +23,11 @@ impl RuleDefinition for FixTrunc {
         "Fix `trunc()` usage based on type"
     }
 
-    fn get_node(&self, root: &Root) -> Result<SyntaxNode, RuleError> {
-        root.procedure()
+    fn find(&self, root: &Root, ctx: &DboAnalyzeContext) -> Result<Vec<RuleMatch>, RuleError> {
```
Comment (justahero) [inline src/rules/builtins.rs:26]: My suggestion is to rename this method to be consistent with how the iterator `find` works, which returns a single `Option` with an inner item, instead of a list of items.

Comment (KieranKaelin) [reply src/rules/builtins.rs:26]: What other name would you choose in this case? Something like `filter`?

**Review by justahero — CHANGES_REQUESTED** [review]
Overall looks good to me, only one nitpick (name of the method).

File: src/rules/builtins.rs (hunk 1 above)
Comment (KieranKaelin) [reply src/rules/builtins.rs:26]: Good point, will do! Regarding the empty `Vec`, you already recommended it once, I will tackle it soon-ish (#75).
